### PR TITLE
add rendering of the documentation on Read the Docs

### LINKED ISSUE #11: Set up ReadTheDocs page
The subdomain https://nest-extension-module.readthedocs.io/ has been registered, but a ``conf.py`` file still needs to be added to the repository to make the documentation render properly. It should then also be checked for proper rendering and whether the table of contents is complete.

### PR DESCRIPTION
**Pull request by clinssen**
Fixes #11.

You can see the rendered version at: https://nest-extension-module.readthedocs.io/en/latest/index.html

It would be nice to also add some items from the NEST Simulator documentation, such as the license, how to find help, and HBP and other acknowledgements. @jessica-mitchell: do you have any suggestions for transcluding this content "live" from the nest-simulator repository?

### CODE REVIEW

**Comment by jessica-mitchell** [comment]
@clinssen I'm afraid I don't know of a solution to include content from one repo into another. I'd suggest for now just linking to the content; I can try to look deeper into it this.

**Comment by clinssen** [comment]
@jessica-mitchell: which sections would you recommend to include as a minimum? I could grab those files using some custom lines in ``conf.py`` from the nest-simulator repository, so they wouldn't be duplicated in this repository, but this would be sensitive to changing the links (like the recent move from ``doc/`` to ``doc/userdoc/``).

How about just:
* About NEST Simulator (this would link back to https://nest-simulator.readthedocs.org/)
* License

**Comment by jessica-mitchell** [comment]
> @jessica-mitchell: which sections would you recommend to include as a minimum? I could grab those files using some custom lines in `conf.py` from the nest-simulator repository, so they wouldn't be duplicated in this repository, but this would be sensitive to changing the links (like the recent move from `doc/` to `doc/userdoc/`).

I haven't found any nice way to include content from external repositories, so adding some code in conf.py might be the best way to go.
> 
> How about just:
> 
>     * About NEST Simulator (this would link back to https://nest-simulator.readthedocs.org/)
Do you want to just link to this page? You could use intersphinx to link to it (I believe the homepage of NEST doc would be :ref:\`_unique-identifier_:/index.rst\`).

> 
>     * License

Those seem fine to me; Acknowledgments may be another to consider, but I don't know if that's necessary.

**Review by jougs — APPROVED** [review]

**Comment by jougs** [comment]
The CI failures should be fixed by recent commits to master. @clinssen: could you please pull?

**Comment by jougs** [comment]
Many thanks!

**Pull request merged**
